title: Web App
description: Web App Development Textbook with Labs
theme: just-the-docs
color_scheme: foo

url: https://github.com/Keshvadi/testbook

aux_links:
  Template Repository: https://github.com/Keshvadi
