title: Web App
description: Web App Development Textbook with Labs
theme: just-the-docs
remote_theme: pmarsceill/just-the-docs
color_scheme: custom

url: https://github.com/Keshvadi/testbook

aux_links:
  "Sina Keshvadi": https://github.com/Keshvadi
  "Dark Mode": 
    - "#"
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - package.json
  - vendor/bundle/
  - yarn.lock